markdown: kramdown
highlighter: true
permalink: /:year/:month/:day/:title.html
name: "tzungtzu"
markdown: kramdown
highlighter: rouge


#每页显示的文章数
paginate: 5


author: "tzungtzu"
atom-baseurl: "http://tzungtzu.com"
disqus: "gopherwood"

navigations:
  - title: Archive
    class: fa fa-list-ul
    href: /archive.html
  - title: Tags
    class: fa fa-tags
    href: /tags.html
  - title: About
    class: fa fa-user
    href: /about.html
  - title: Gallery
    class: fa fa-film
    href: http://foto.lhzhang.com
  - title: Blogroll
    class: fa fa-link
    href: /links.html
  - title: Subscribe
    class: fa fa-rss
    href: /atom.xml

